apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: altinity-clickhouse-operator
  namespace: marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  # Which namespace to look into for operator(s) in quay.io
  # Specify registryNamespace="${QUAY_NAMESPACE}"
  registryNamespace: sunsingerus

  publisher: Altinity
  displayName: ClickHouse Operator
  # The name of the k8s secret object that contains the authorization token to access private repositories.
  # More details: https://github.com/operator-framework/operator-marketplace/blob/master/docs/how-to-authenticate-private-repositories.md
#  authorizatonToken:
#    secretName: "name of the kind: Secret object"
