apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: clickhouse-operator-subscription

# So far looks like Subscription is expected to ber in the namespace where operator is expected
#  namespace: default
  namespace: marketplace
spec:
  # Specify package name to look for in 'kind: OperatorSource'
  name: clickhouse-operator
  # Specify channel in this package
  channel: latest

  # Specify the name of 'kind: OperatorSource' created earlier.
  # Recommended name is "${QUAY_NAMESPACE}-operators"
  source: sunsingerus-operators
  # Specify namespace where 'kind: OperatorSource' created earlier is located
  sourceNamespace: marketplace

